### ISSUE TITLE
Custom route prefix

### ISSUE THREAD

**Issue by elynnaie** [ssmulders/hashed-passport#1]
Love this package! Would it be possible to allow a custom route prefix with this package? I ask because our passport routes are prefixed using `Passport::routes(null, ['prefix' => 'api/oauth']);` so that the routes are, e.g., `api/oauth/token` instead of `oauth/token`. However, this package only provides the route for `oauth/token`. Any way to make that work?

**Comment by ssmulders** [comment]
Actually... you gave me an idea. Instead of adding the routes to the package, all you'd need to do is change the `Passport::routes()` to `Passport::routes(NULL, ['middleware' => ['hashed_passport']])`

In your case, this should do the trick:
`Passport::routes(NULL, ['prefix' => 'api/oauth', 'middleware' => ['hashed_passport']]);`

The 'old' route will still be active/available right now but I'll update the package to use this method instead of baked routes! Much cleaner and easier. Thanks :)

**Comment by elynnaie** [comment]
Looks like it works for me. Great solution!
